version: "3"

# volumes:
#   nestjs-node-modules:

services:
  docker-test:
    image: vite-image:latest
    working_dir: "/usr/vite-project"
    ports:
      - 5173:5173
    build:
      context: .
      dockerfile: Dockerfile
    # src配下をvolumesとしてmountする
    # https://github.com/docker/compose/issues/8533
    volumes:
      # - src-volume:/usr/vite-project/src
      - ./vite-project/src/:/usr/vite-project/src/
    restart: always
    container_name: docker-vite
    tty: true
    env_file: ./vite-project/.env

volumes:
  src-volume: