version: "3"

# volumes:
#   nestjs-node-modules:

services:
  client:
    image: vite-client-image:latest
    container_name: client-vite
    working_dir: "/usr/vite-project"
    ports:
      - 5173:5173
    build:
      context: ./client
      dockerfile: Dockerfile
    # src配下をvolumesとしてmountする
    # https://github.com/docker/compose/issues/8533
    volumes:
      # - src-volume:/usr/vite-project/src
      - ./client/vite-project/src/:/usr/vite-project/src/
      # - ./client/vite-project/:/usr/vite-project/
    restart: always
    tty: true
    env_file: ./client/vite-project/.env
    # depends_onについて　https://gotohayato.com/content/533/
    depends_on:
      - server
  server:
    image: vite-server-image:latest
    container_name: vite-server
    working_dir: "/server"
    ports:
      - 8080:8080
    build:
      context: ./server
      dockerfile: Dockerfile
    # src配下をvolumesとしてmountする
    # https://github.com/docker/compose/issues/8533
    volumes:
      # - src-volume:/usr/vite-project/src
      - ./server/server.js:/server/server.js
    restart: always
    tty: true

volumes:
  src-volume: