version: "3"

services:
  docker-test:
    image: vite-image:latest
    working_dir: "/usr/vite-project"
    ports:
      - 5173:5173
    # volumes:
      # - ./vite-project:/usr/vite-project/
    restart: always
    container_name: docker-vite
    tty: true